export const PRESET_STOPS = [
  {
    restaurant_name: 'Tai Cheong Bakery',
    address: '35 Johnston Road, Wan Chai',
    lat: 22.2743,
    lng: 114.1725,
    box_count: 8,
    route_order: 1,
    status: 'completed',
    pickup_window_start: '21:00',
    pickup_window_end: '21:15',
    eta: '21:00',
  },
  {
    restaurant_name: 'Kee Wah Bakery',
    address: '6 Hennessy Road, Wan Chai',
    lat: 22.277,
    lng: 114.1752,
    box_count: 5,
    route_order: 2,
    status: 'completed',
    pickup_window_start: '21:15',
    pickup_window_end: '21:30',
    eta: '21:15',
  },
  {
    restaurant_name: 'Saint Honore Cake Shop',
    address: '12 Wellington Street, Central',
    lat: 22.2847,
    lng: 114.1543,
    box_count: 6,
    route_order: 3,
    status: 'pending',
    pickup_window_start: '21:30',
    pickup_window_end: '21:45',
    eta: '21:30',
  },
  {
    restaurant_name: 'A1 Bakery',
    address: '17 Hillwood Road, Tsim Sha Tsui',
    lat: 22.2978,
    lng: 114.172,
    box_count: 4,
    route_order: 4,
    status: 'pending',
    pickup_window_start: '21:45',
    pickup_window_end: '22:00',
    eta: '21:45',
  },
  {
    restaurant_name: 'Bakehouse',
    address: '1 Tai Wo Street, Wan Chai',
    lat: 22.2762,
    lng: 114.1822,
    box_count: 7,
    route_order: 5,
    status: 'pending',
    pickup_window_start: '22:00',
    pickup_window_end: '22:15',
    eta: '22:00',
  },
  {
    restaurant_name: 'Peninsula Boutique',
    address: 'Salisbury Road, Tsim Sha Tsui',
    lat: 22.2953,
    lng: 114.172,
    box_count: 6,
    route_order: 6,
    status: 'pending',
    pickup_window_start: '22:15',
    pickup_window_end: '22:30',
    eta: '22:15',
  },
  {
    restaurant_name: "Maxim's Palace",
    address: '2 Edinburgh Place, Central',
    lat: 22.2813,
    lng: 114.158,
    box_count: 9,
    route_order: 7,
    status: 'pending',
    pickup_window_start: '22:30',
    pickup_window_end: '22:45',
    eta: '22:30',
  },
];